// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbGj7QAr7s_axLJkAylaMIbD6S-1aEE-s',
    appId: '1:548848905061:web:05632da1b580bc44bb4f8c',
    messagingSenderId: '548848905061',
    projectId: 'basic-banking-app-eb2a6',
    authDomain: 'basic-banking-app-eb2a6.firebaseapp.com',
    storageBucket: 'basic-banking-app-eb2a6.appspot.com',
    measurementId: 'G-W8KDEKGP04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhAU_r5etnEktPb-B0S25pp2cv1HUP2tk',
    appId: '1:548848905061:android:0520ed70505e6366bb4f8c',
    messagingSenderId: '548848905061',
    projectId: 'basic-banking-app-eb2a6',
    storageBucket: 'basic-banking-app-eb2a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzEEwTrzRw5Gl0E14lWG5UjOzy0r7iXq4',
    appId: '1:548848905061:ios:8ede00285525ef3dbb4f8c',
    messagingSenderId: '548848905061',
    projectId: 'basic-banking-app-eb2a6',
    storageBucket: 'basic-banking-app-eb2a6.appspot.com',
    iosClientId: '548848905061-qtcfmpskc4ov38kcld4vcj8tfb33rr6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicBankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzEEwTrzRw5Gl0E14lWG5UjOzy0r7iXq4',
    appId: '1:548848905061:ios:8ede00285525ef3dbb4f8c',
    messagingSenderId: '548848905061',
    projectId: 'basic-banking-app-eb2a6',
    storageBucket: 'basic-banking-app-eb2a6.appspot.com',
    iosClientId: '548848905061-qtcfmpskc4ov38kcld4vcj8tfb33rr6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicBankingApp',
  );
}
